import type { NextPage } from 'next';
import Head from 'next/head';

import { HeroSection } from '@/sections';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pham Thien Duy: Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static/images/favicon.ico" />
      </Head>
      <HeroSection />
    </>
  );
};

export default Home;
