/* eslint-disable tailwindcss/no-custom-classname */
import type { NextPage } from 'next';
import Head from 'next/head';

import { HeroSection, InfoSection } from '@/sections';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pham Thien Duy: Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static/images/favicon.ico" />
      </Head>
      <div className="font-railway background p-4  text-gray-400 dark:bg-gray-900 dark:text-gray-200">
        <HeroSection />
        <InfoSection />
      </div>
    </>
  );
};

export default Home;
